#create the config map for scripts used by all workload to manage redis
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-scripts
  annotations:
    field.cattle.io/description: the scripts to manage redis
binaryData:
  start_redis: >- 
{{ include "redis.start_redis" . | b64enc | indent 4 }}
  reset_redis: >- 
{{ include "redis.reset_redis" . | b64enc | indent 4 }}
  redis_startup: >- 
{{ include "redis.redis_startup" . | b64enc | indent 4 }}
  redis_liveness: >- 
{{ include "redis.redis_liveness" . | b64enc | indent 4 }}
