#create the workload 
#get the total number of workloads
{{- $workloads := 0 }}
{{- range $i,$workload := $.Values.redis.workloads }}
    {{- $workloads = add $workloads 1}}
{{- end }}
#declare the variables 
{{- $workload_name := "" }}
{{- $workload_conf_name := "" }}
{{- $conf_name := "" }}
{{- $workload_index := 0 }}
{{- $node_index := 0 }}
{{- $node := 0 }}
{{- $ports := list }}
{{- $port := 0 }}
{{- $ports_len := 0 }}
{{- $redis_conf := (get $.Values.redis "redis.conf") | default dict  }}
{{- $cluster_enabled :=  false }}
{{- $start_port := $.Values.redis.port | default 6379 |int }}
{{- $servers := $.Values.redis.servers | default 1 | int }}
{{- $end_port := add $start_port $servers | int  }}
{{- $redisport_conf := dict }}
{{- $redisserver_conf := dict }}
{{- $save := "\"\"" }}
{{- $appendonly := "no" }}
{{- $cluster_enabled :=  false }}
{{- $startupProbe :=  $.Values.redis.startupProbe | default dict }}
{{- $livenessProbe :=  $.Values.redis.livenessProbe | default dict }}
{{- $has_storage := and $.Values.redis.volume $.Values.redis.volume.storage  }}
{{- $replicas := $.Values.redis.replicas | default 1 | int }}
#include all the cluster master list(the node list doesn't include the port) for the redis clusters
#more than one redis clusters can use the same cluster master list , but with different port
{{- $cluster_masters_list := list }}
{{- $cluster_masters_list_len := 0 }}

#find all the cluster master list and add them to cluser_masters_list
{{- range $i,$cluster := $.Values.redis.redisClusters | default list }}
    {{- $nodes_len := 0 }}
    {{- range $j,$node := $cluster.servers }}
        {{- $nodes_len = add $nodes_len 1 }}
    {{- end }}
    {{- $cluster_groups_len := div $nodes_len (add ($cluster.clusterReplicas | default 1 ) 1 ) | int }}
    {{- $cluster_masters := list }}
    #Get the master node(not  includeing the port) list
    {{- range $j,$master_index := until $cluster_groups_len }}
        {{- $cluster_node := index $cluster.servers $master_index }}
        #remove the port 
        {{- $cluster_node = index (regexSplit ":" $cluster_node -1) 0 }}
        #replace 'redis' with Release.Name
        {{- $cluster_node = print $.Release.Name (trimPrefix "redis" $cluster_node) }}
        {{- $cluster_masters = append $cluster_masters $cluster_node}}
    {{- end }}
    #add the master node list into cluster_masters_list if the list doesn't exist before
    {{- $masters_exists := false }}
    {{- range $j,$masters := $cluster_masters_list }}
        {{- $exists := true }}
        {{- range $k,$node := $cluster_masters }}
            {{- if not (has $node $masters) }}
                {{- $exists = false}}
            {{- end }}
        {{- end }}
        {{- if $exists }}
            {{- $masters_exists = true}}
        {{- end }}
    {{- end }}
    {{- if not $masters_exists }}
        {{- $cluster_masters_list = append $cluster_masters_list $cluster_masters }}
        {{- $cluster_masters_list_len = add $cluster_masters_list_len 1 }}
    {{- end }}
{{- end }}

{{- range $i,$workload := $.Values.redis.workloads }}
    #workload index is 1 based
    #get the workload_name and workload_conf_name
    {{- $workload_index = add $i 1 }}
    {{- if le $workloads 1 }}
        {{- $workload_name = $.Release.Name }}
        {{- $workload_conf_name = "redis" }}
    {{- else }}
---
        {{- if le $workloads 9 }}
            {{- $workload_name = print $.Release.Name $workload_index }}
            {{- $workload_conf_name = print "redis" $workload_index }}
        {{- else if le $workload_index 9 }}
            {{- $workload_name = print $.Release.Name "0" $workload_index }}
            {{- $workload_conf_name = print "redis0" $workload_index }}
        {{ else }}
            {{- $workload_name = print $.Release.Name $workload_index }}
            {{- $workload_conf_name = print "redis" $workload_index }}
        {{- end }}
    {{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $workload_name }}
spec:
  selector:
    matchLabels:
      #the label for the workload, include all the replicas
      redis.workloadselector: {{ $.Release.Namespace}}-{{ $workload_name }}
      # the label for all the pods created by all workloads
      redis.releaseselector: {{ $.Release.Namespace}}-{{ $.Release.Name }}
      #
      {{- range $k,$cluster := get $.Values.redis "redisClusters" | default list }}
          #find all the ports used by the redis cluster
          {{- $ports = list }}
          {{- $ports_len = 0 }}
          {{- range $l,$redis_node := $cluster.servers }}
                #get the configured redis_node name from the configuration.
                #the redis_node name should be redis{workload_index}-{replica-index}
                {{- $node = index (regexSplit ":" $redis_node -1) 0 }}
                #get the configured port number 
                {{- $port = (index (regexSplit ":" $redis_node -1) 1) | int }}
                #find the node_index, because node_index is 1 based, but $i is 0 based, so sub 1 from node_index
                {{- if contains "-" $node }}
                    {{- $node_index = (sub (trimPrefix "redis" (index (regexSplit "-" $node -1) 0) | int) 1) }}
                {{- else }}
                    {{- $node_index = (sub (trimPrefix "redis" $node | int) 1) }}
                {{- end }}
                {{- if and (eq $i $node_index) (not (has $port $ports)) }}
                    {{- $ports = append $ports $port }}
                    {{- $ports_len = add $ports_len 1 }}
                {{- end }}
          {{- end }}
          #if have ports used by the redis cluster,create a label for each port used by the redis cluster
          #this label will be used as the selector by the rediscluster clusterip service 
          {{- range $l,$p := $ports  }}
              {{- if eq $ports_len 1 }}
      {{ $.Release.Name}}.rediscluster.{{ $cluster.name }}.selector: apps.statefulset-{{ $.Release.Namespace}}-{{ $.Release.Name}}-rediscluster-{{ $cluster.name }}
              {{- else }}
      {{ $.Release.Name}}.rediscluster.{{ $cluster.name }}.{{ $p }}.selector: apps.statefulset-{{ $.Release.Namespace}}-{{ $.Release.Name}}-rediscluster-{{ $cluster.name }}-{{ $p }}
              {{- end }}
          {{- end}}
      {{- end }}
  podManagementPolicy: OrderedReady
  replicas: {{ $replicas}}
  revisionHistoryLimit: 10
  serviceName: {{ $workload_name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        #same as matchLabels
        redis.workloadselector: {{ $.Release.Namespace}}-{{ $workload_name }}
        redis.releaseselector: {{ $.Release.Namespace}}-{{ $.Release.Name }}
      {{- range $k,$cluster := get $.Values.redis "redisClusters" | default list }}
          {{- $ports = list }}
          {{- $ports_len = 0 }}
          {{- range $l,$redis_node := $cluster.servers }}
                {{- $node = index (regexSplit ":" $redis_node -1) 0 }}
                {{- $port = (index (regexSplit ":" $redis_node -1) 1) | int }}
                {{- if contains "-" $node }}
                    {{- $node_index = (sub (trimPrefix "redis" (index (regexSplit "-" $node -1) 0) | int) 1) }}
                {{- else }}
                    {{- $node_index = (sub (trimPrefix "redis" $node | int) 1) }}
                {{- end }}
                {{- if and (eq $i $node_index) (not (has $port $ports)) }}
                    {{- $ports = append $ports $port }}
                    {{- $ports_len = add $ports_len 1 }}
                {{- end }}
          {{- end }}
          {{- range $l,$p := $ports  }}
              {{- if eq $ports_len 1 }}
        {{ $.Release.Name}}.rediscluster.{{ $cluster.name }}.selector: apps.statefulset-{{ $.Release.Namespace}}-{{ $.Release.Name}}-rediscluster-{{ $cluster.name }}
              {{- else }}
        {{ $.Release.Name}}.rediscluster.{{ $cluster.name }}.{{ $p }}.selector: apps.statefulset-{{ $.Release.Namespace}}-{{ $.Release.Name}}-rediscluster-{{ $cluster.name }}-{{ $p }}
              {{- end }}
          {{- end}}
      {{- end }}
    spec:
      {{- if and (gt $replicas 1 ) $.Values.redis.topologySpreadConstraints }}
      #only include the topology if replicas is greater than 1
      topologySpreadConstraints:
          {{- range $i,$constraint := $.Values.redis.topologySpreadConstraints }}
              {{- if eq $i 0 }}
      #the master and its slaves must be running on different nodes
      - maxSkew: {{ $constraint.maxSkew | default 1 }}
        topologyKey: {{ $constraint.topologyKey }}
        {{- if eq $constraint.whenUnsatisfiable "DoNotSchedule" }}
        minDomains: {{ $constraint.minDomains | default 1 }}
        {{- end }}
        whenUnsatisfiable: {{ $constraint.whenUnsatisfiable }}
        labelSelector:
          matchLabels:
            redis.workloadselector: {{ $.Release.Namespace}}-{{ $workload_name }}
              {{- else if le $i $cluster_masters_list_len }}
      - maxSkew: {{ $constraint.maxSkew | default 1 }}
        topologyKey: {{ $constraint.topologyKey }}
        {{- if eq $constraint.whenUnsatisfiable "DoNotSchedule" }}
        minDomains: {{ $constraint.minDomains | default 1 }}
        {{- end }}
        whenUnsatisfiable: {{ $constraint.whenUnsatisfiable }}
        labelSelector:
          matchExpressions:
            - key: statefulset.kubernetes.io/pod-name
              operator: In
              values:
                {{- range $k,$node := index $cluster_masters_list (sub $i 1)}}
                - {{ $node }}
                {{- end }}
              {{- end }}
          {{- end }}
      {{- end }}
      containers:
        - args:
          - /usr/local/redis/bin/start_redis
          {{- if $.Values.redis.envs }}
          env:
            - name: RELEASE_TIME
              value: {{ now | date "2006-01-02T15:04:05" | quote }}
              {{- range $index,$env := $.Values.redis.envs | default dict }}
            - name: {{ $env.name }}
              value: {{ $env.value }}
              {{- end }}
          {{- end }}
          workingDir: /usr/local/redis
          image: {{ $.Values.redis.image }}
          imagePullPolicy: Always
          name: {{ $workload_name }}
          {{- if $.Values.redis.resources }}
          resources:
{{ $.Values.redis.resources | toYaml | indent 12 }}
          {{- end }}
          securityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            capabilities: {}
            runAsUser: 999
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          stdin: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 999
            runAsNonRoot: true
            runAsUser: 999
          volumeMounts:
          - mountPath: /usr/local/redis/bin
            name: redis-scripts
          - mountPath: /usr/local/redis/conf/redis_common.conf
            name: redis-confs
            subPath: redis_common.conf
          {{- range $i,$port := untilStep $start_port $end_port 1 }}
              {{- range $j,$replica_index := until $replicas }}
                  {{- if eq $replicas 1 }}
                      {{- $conf_name = $workload_conf_name }}
                  {{- else if le $replicas 9 }}
                      {{- $conf_name = print $workload_conf_name "_" $replica_index }}
                  {{- else if le $replica_index 9 }}
                      {{- $conf_name = print $workload_conf_name "_0" $replica_index }}
                  {{- else }}
                      {{- $conf_name = print $workload_conf_name "_" $replica_index }}
                  {{- end }}
                  {{- if eq $replicas 1 }}
                      {{- if eq $servers 1 }}
          - mountPath: /usr/local/redis/conf/redis.conf
                      {{- else }}
          - mountPath: /usr/local/redis/{{ $port }}/conf/redis.conf
                      {{- end }}
            name: redis-confs
            subPath: {{ $conf_name }}_{{ $port}}.conf
                  {{- else }}
                      {{- if eq $servers 1 }}
          - mountPath: /usr/local/redis/conf/{{ print $workload_name "-" $replica_index }}/redis.conf
                      {{- else }}
          - mountPath: /usr/local/redis/{{ $port }}/conf/{{ print $workload_name "-" $replica_index }}/redis.conf
                      {{- end }}
            name: redis-confs
            subPath: {{ $conf_name }}_{{ $port}}.conf
                  {{- end }}
              {{- end }}
          {{- end }}
          {{- if $has_storage  }}
              {{- range $i,$port := untilStep $start_port $end_port 1 }}
                  {{- $redisport_conf = (get $.Values.redis (print "redis_" $port ".conf")) | default dict}}
                  {{- $redisserver_conf = (get $.Values.redis (print $workload_conf_name "_" $port ".conf")) | default dict }}
                  {{- $save = (get $redisserver_conf "save") | default (get $redisport_conf "save") | default (get $redis_conf "save") | default "\"\"" }}
                  {{- $appendonly = (get $redisserver_conf "appendonly") | default (get $redisport_conf "appendonly") | default (get $redis_conf "appendonly") | default "no" }}
                  {{- $cluster_enabled = and $has_storage (eq ((get $redisserver_conf "cluster-enabled") | default (get $redisport_conf "cluster-enabled") | default (get $redis_conf "cluster-enabled") | default "no") "yes") }}
                  {{- if not $save }}
                      {{- $save = "\"\"" }}
                  {{- end }}
                  {{- if or (ne $save "\"\"")  (ne $appendonly  "no") $cluster_enabled }}
                      {{- if eq $servers 1 }}
          - mountPath: /usr/local/redis/data
            {{- if eq $replicas 1 }}
            name: redis-data
            {{- else }}
            name: {{ $workload_name}}-data
            {{- end }}
            subPath: data
                      {{- else }}
          - mountPath: /usr/local/redis/{{ $port }}/data
            {{- if eq $replicas 1 }}
            name: redis-data
            {{- else }}
            name: {{ $workload_name}}-data
            {{- end }}
            subPath: {{ $port }}/data
                      {{- end }}
                  {{- end }}
              {{- end }}
              {{- range $i,$port := untilStep $start_port $end_port 1 }}
                  {{- if eq $servers 1 }}
          - mountPath: /usr/local/redis/logs
            {{- if eq $replicas 1 }}
            name: redis-data
            {{- else }}
            name: {{ $workload_name}}-data
            {{- end }}
            subPath: logs
                  {{- else }}
          - mountPath: /usr/local/redis/{{ $port }}/logs
            {{- if eq $replicas 1 }}
            name: redis-data
            {{- else }}
            name: {{ $workload_name}}-data
            {{- end }}
            subPath: {{ $port }}/logs
                  {{- end }}
              {{- end }}
          {{- end }}
          {{- if not ($.Values.redis.reset | default false) }}
          startupProbe:
            failureThreshold: {{ $startupProbe.failureThreshold | default 30 }}
            successThreshold: {{ $startupProbe.successThreshold | default 1 }}
            initialDelaySeconds: {{ $startupProbe.initialDelaySeconds | default 0 }}
            timeoutSeconds: {{ $startupProbe.timeoutSeconds | default 1 }}
            periodSeconds: {{ $startupProbe.timeoutSeconds | default 1 }}
            exec:
              command:
                - /usr/local/redis/bin/redis_startup
          livenessProbe:
            failureThreshold: {{ $livenessProbe.failureThreshold | default 2 }}
            successThreshold: {{ $livenessProbe.successThreshold | default 1 }}
            initialDelaySeconds: {{ $livenessProbe.initialDelaySeconds | default 1 }}
            timeoutSeconds: {{ $livenessProbe.timeoutSeconds | default 1 }}
            periodSeconds: {{ $livenessProbe.periodSeconds | default 2 }}
            exec:
              command:
                - /usr/local/redis/bin/redis_liveness
          {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 999
      terminationGracePeriodSeconds: 30
      {{- if $workload.affinity }}
      affinity:
{{ $workload.affinity | toYaml | indent 8 }}
      {{- end }}
      volumes:
      - configMap:
          defaultMode: 365
          name: {{ $.Release.Name }}-scripts
        name: redis-scripts
      - configMap:
          defaultMode: 292
          name: {{ $.Release.Name }}-confs
        name: redis-confs
      {{- if $has_storage  }}
          {{- if eq $replicas 1 }}
      - name: redis-data
        persistentVolumeClaim:
          claimName: {{ $workload_name }}-data
          type: persistentvolumeclaim
          {{- else }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: {{ $workload_name }}-data
        namespace: {{ $.Release.Namespace }}
      spec:
        accessModes:
          - {{ $.Values.redis.volume.accessMode | default "ReadWriteOnce" }}
        resources:
          requests:
            storage: {{ $.Values.redis.volume.storage}}
        storageClassName: {{ $.Values.redis.volume.storageClassName | default "managed-csi-retain" }}
        volumeMode: {{ $.Values.redis.volume.volumeMode | default "Filesystem" }}
          {{- end }}
      {{- end }}
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
{{- end}}
