{{- $workloads := $.Values.redis.workloads | default 1 |int }}
{{- $redisName := $.Release.Name }}
{{- range $i,$redisIndex := untilStep 1 (add $workloads 1 | int) 1 }}
{{- if le $workloads 1 }}
{{- $redisName = $.Release.Name }}
{{- else }}
---
{{- if le $workloads 9 }}
{{- $redisName = print $.Release.Name $redisIndex }}
{{- else if le $redisIndex 9 }}
{{- $redisName = print $.Release.Name "0" $redisIndex }}
{{ else }}
{{- $redisName = print $.Release.Name $redisIndex }}
{{- end }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $redisName}}
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: default
      port: 42
      protocol: TCP
      targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: apps.statefulset-{{ $.Release.Namespace }}-{{ $redisName}}
  sessionAffinity: None
  type: ClusterIP
{{- end }}
