{{- $replicas := $.Values.redis.replicas | default 1 | int }}
{{- if and $.Values.redis.volume $.Values.redis.volume.storage  (eq $replicas 1) }}
{{- $workloads := 0 }}
{{- range $i,$workload := $.Values.redis.workloads }}
    {{- $workloads = add $workloads 1}}
{{- end }}
{{- $redis_name := $.Release.Name }}
{{- $redis_index := 0 }}
{{- range $i,$workload := $.Values.redis.workloads }}
    {{- $redis_index = add $i 1 }}
    {{- if le $workloads 1 }}
        {{- $redis_name = $.Release.Name }}
    {{- else }}
---
        {{- if le $workloads 9 }}
            {{- $redis_name = print $.Release.Name $redis_index }}
        {{- else if le $redis_index 9 }}
            {{- $redis_name = print $.Release.Name "0" $redis_index }}
        {{ else }}
            {{- $redis_name = print $.Release.Name $redis_index }}
        {{- end }}
    {{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $redis_name }}-data
spec:
  accessModes:
    - {{ $.Values.redis.volume.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $.Values.redis.volume.storage}}
  storageClassName: {{ $.Values.redis.volume.storageClassName | default "managed-csi-retain" }}
  volumeMode: {{ $.Values.redis.volume.volumeMode | default "Filesystem" }}
{{- end }}
{{- end }}
