{{- if (hasKey $.Values.redis "imagepull") }}
{{- $data := dict "auths" (dict "dhi.io"  (dict "username" ($.Values.redis.imagepull.username ) "password" ($.Values.redis.imagepull.password ) )) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-secret-imagepull
  namespace: {{ $.Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ toJson $data | b64enc }}
{{- end }}
