#create a pod disruption budget for each workload whose replica is greater than 1
{{- $replicas := $.Values.redis.replicas | default 1 | int }}
{{- if gt $replicas 1 }}
{{- $workloads := 0 }}
{{- $workload_index := 0 }}
{{- $workload_name := "" }}
#find the total number of workloads
{{- range $i,$workload := $.Values.redis.workloads }}
    {{- $workloads = add $workloads 1 }}
{{- end }}

{{- range $i,$workload := $.Values.redis.workloads }}
    #workload_index is 1 based
    {{- $workload_index = add $i 1 }}
    #get the workload name based on release name and workload_index
    {{- if le $workloads 1 }}
        {{- $workload_name = $.Release.Name }}
    {{- else }}
---
        {{- if le $workloads 9 }}
            {{- $workload_name = print $.Release.Name $workload_index }}
        {{- else if le $workload_index 9 }}
            {{- $workload_name = print $.Release.Name "0" $workload_index }}
        {{ else }}
            {{- $workload_name = print $.Release.Name $workload_index }}
        {{- end }}
    {{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $workload_name}}
spec:
  minAvailable: {{ sub $replicas 1 }}
  selector:
    matchLabels:
      redis.workloadselector: {{ $.Release.Namespace}}-{{ $workload_name }}
{{- end }}
{{- end }}
