{{- $workloads := 0 }}
{{- range $i,$workload := $.Values.redis.workloads }}
    {{- $workloads = add $workloads 1}}
{{- end }}
{{- $start_port := $.Values.redis.port | default 6379 |int }}
{{- $servers := $.Values.redis.servers | default 1 | int }}
{{- $end_port := add $start_port $servers | int  }}
{{- $redis_name := $.Release.Name }}
{{- $redis_index := 0 }}
{{- $node_index := 0 }}
{{- $node := "" }}
{{- $cluster_node := false }}
{{- range $i,$workload := $.Values.redis.workloads }}
    {{- $redis_index = add $i 1 }}
    {{- if le $workloads 1 }}
        {{- $redis_name = $.Release.Name }}
    {{- else }}
---
        {{- if le $workloads 9 }}
            {{- $redis_name = print $.Release.Name $redis_index }}
        {{- else if le $redis_index 9 }}
            {{- $redis_name = print $.Release.Name "0" $redis_index }}
        {{ else }}
            {{- $redis_name = print $.Release.Name $redis_index }}
        {{- end }}
    {{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $redis_name}}
spec:
  clusterIP: {{ get $workload "clusterip" }}
  clusterIPs:
    - {{ get $workload "clusterip" }}
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    {{- range $j,$port := untilStep $start_port $end_port 1 }}
    - name: port-{{ $port }}
      port: {{ $port }}
      protocol: TCP
      targetPort: {{ $port }}
      {{- range $k,$cluster := get $.Values.redis "redis-clusters" }}
          {{- $cluster_node = false }}
          {{- range $l,$redis_node := $cluster.servers }}
                {{- $node = index (regexSplit ":" $redis_node -1) 0 }}
                {{- $node_index = (sub (trimPrefix "workload" $node | int) 1) }}
                {{- if and (eq $i $node_index) (hasSuffix (print ":" $port) $redis_node) }}
                    {{- $cluster_node = true }}
                {{- end }}
          {{- end }}
          {{- if $cluster_node }}
    - name: port-{{ add $port 10000 }}
      port: {{ add $port 10000 }}
      protocol: TCP
      targetPort: {{ add $port 10000 }}
          {{- end}}
      {{- end }}
    {{- end }}
  selector:
    workload.user.cattle.io/workloadselector: apps.statefulset-{{ $.Release.Namespace }}-{{ $redis_name}}
  sessionAffinity: None
  type: ClusterIP
{{- end }}
