#create a config map for all workloads
#find the number of workloads
{{- $workloads := 0 }}
{{- range $i,$workload := $.Values.redis.workloads }}
    {{- $workloads = add $workloads 1}}
{{- end }}
#get the start port and end port based on configured port number and the number of servers running in each pod
{{- $start_port := $.Values.redis.port | default 6379 |int }}
{{- $servers := $.Values.redis.servers | default 1 | int }}
{{- $end_port := add $start_port $servers | int  }}

#get the configured common redis conf 
{{- $redis_conf := (get $.Values.redis "redis.conf") | default dict }}
#the configured redis conf for specified port
{{- $redisport_conf := "" }}
#the configured redis conf for specified workload and port
{{- $redisworkload_conf := "" }}
{{- $save := "\"\"" }}
{{- $appendonly := "no" }}
{{- $cluster_enabled :=  false }}
{{- $clusterip :=  "" }}
#whether has persistent storage
{{- $has_storage := and $.Values.redis.volume $.Values.redis.volume.storage  }}
{{- $replicas := $.Values.redis.replicas | default 1 | int }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-confs
  annotations:
    field.cattle.io/description: redis configurations
data:
  #The only difference between workload_conf_name and workload_name is workload_conf_name uses prefix 'redis', but workload_name uses 'releasename'
  #because the properties defined in the config map should be consistent for different release name
  {{- $workload_conf_name := "" }}
  {{- $workload_name := $.Release.Name }}
  {{- $conf_name := $.Release.Name }}
  {{- range $i,$port := untilStep $start_port $end_port 1 }}
      #get configured redis port conf 
      {{- $redisport_conf = (get $.Values.redis (print "redis_" $port ".conf")) | default dict }}
      {{- range $j,$workload_index := untilStep 1 (add $workloads 1 | int) 1 }}
          #get the workload name and workload_conf_name
          {{- if le $workloads 1 }}
              {{- $workload_name = $.Release.Name }}
              {{- $workload_conf_name = "redis" }}
          {{- else }}
              {{- if le $workloads 9 }}
                  {{- $workload_name = print $.Release.Name $workload_index }}
                  {{- $workload_conf_name = print "redis" $workload_index }}
              {{- else if le $workload_index 9 }}
                  {{- $workload_name = print $.Release.Name "0" $workload_index }}
                  {{- $workload_conf_name = print  "redis0" $workload_index }}
              {{- else }}
                  {{- $workload_name = print $.Release.Name $workload_index }}
                  {{- $workload_conf_name = print "redis" $workload_index }}
              {{- end }}
          {{- end }}
          #get configured redis server conf 
          {{- $redisworkload_conf = (get $.Values.redis (print $workload_conf_name "_" $port ".conf")) | default dict }}
          #get the configured value from server conf, port conf and common conf; otherwise use default value
          {{- $save = (get $redisworkload_conf "save") | default (get $redisport_conf "save") | default (get $redis_conf "save") | default "\"\"" }}
          {{- $appendonly = (get $redisworkload_conf "appendonly") | default (get $redisport_conf "appendonly") | default (get $redis_conf "appendonly") | default "no" }}
          {{- $cluster_enabled = and $has_storage (eq ((get $redisworkload_conf "cluster-enabled") | default (get $redisport_conf "cluster-enabled") | default (get $redis_conf "cluster-enabled") | default "no") "yes") }}
          {{- if not $save }}
              {{- $save = "\"\"" }}
          {{- end }}
          #create a property for each redis server(identified by workload index, replica index and port) running in the pod, 
          #the property name should be {workload_conf_name}_{replica_index}_{port}, replica_index is 0 based and has 2 digits if have more than 9 replicas
          {{- range $k,$replica_index := until $replicas }}
            {{- if eq $replicas 1 }}
                {{- $conf_name = $workload_conf_name }}
            {{- else if le $replicas 9 }}
                {{- $conf_name = print $workload_conf_name "_" $replica_index }}
            {{- else if le $replica_index 9 }}
                {{- $conf_name = print $workload_conf_name "_0" $replica_index }}
            {{- else }}
                {{- $conf_name = print $workload_conf_name "_" $replica_index }}
            {{- end }}
            {{- if and (eq $replicas 1) (get (index $.Values.redis.workloads $j) "clusterip") }}
                {{- $clusterip = (get (index $.Values.redis.workloads $j) "clusterip")  }}
            {{- else }}
                {{- $clusterip = index (get (index $.Values.redis.workloads $j) "clusterips") $replica_index }}
            {{- end }}
  {{ $conf_name }}_{{- $port}}.conf: |-
    include /usr/local/redis/conf/redis_common.conf
    port {{ $port}}
          {{- if eq $servers 1 }}
    pidfile {{ $.Values.pidfolder | default "/data" }}/redis.pid
          {{- else }}
    pidfile {{ $.Values.pidfolder | default "/data" }}/redis_{{ $port }}.pid
          {{- end }}
          {{- if $cluster_enabled }}
    cluster-enabled yes
    cluster-announce-ip {{ $clusterip }}
    cluster-announce-port {{ $port }}
          {{- else }}
    cluster-enabled no
          {{- end }}
          {{- if $redis_conf }}
              {{- range $key,$value := $redis_conf }}
                  {{- if and (ne $key "save") (ne $key "appendonly") (ne $key "cluster-enabled") (not (hasPrefix "_" $key))}}
    {{ $key }} {{ $value }}
                  {{- end }}
              {{- end }}
          {{- end }}
          {{- if $redisport_conf }}
              {{- range $key,$value := $redisport_conf }}
                  {{- if and (ne $key "save") (ne $key "appendonly") (ne $key "cluster-enabled") (not (hasPrefix "_" $key))}}
    {{ $key }} {{ $value }}
                  {{- end }}
              {{- end }}
          {{- end }}
          {{- if $redisworkload_conf }}
              {{- range $key,$value := $redisworkload_conf }}
                  {{- if and (ne $key "save") (ne $key "appendonly") (ne $key "cluster-enabled") (not (hasPrefix "_" $key))}}
    {{ $key }} {{ $value }}
                  {{- end }}
              {{- end }}
          {{- end }}

          {{- if $has_storage  }}
              {{- if or (ne $save "\"\"")  (eq $appendonly "yes") $cluster_enabled }}
                  {{- if eq $servers 1 }}
    dir /usr/local/redis/data
                  {{- else }}
    dir /usr/local/redis/{{ $port }}/data
                  {{- end }}
              {{- else }}
    dir /tmp
              {{- end }}
    appendonly {{ $appendonly }}
    save {{ $save }}
              {{- if eq $servers 1 }}
    logfile /usr/local/redis/logs/redis.log
              {{- else }}
    logfile /usr/local/redis/{{ $port }}/logs/redis.log
              {{- end }}
          {{- else }}
    logfile /tmp/redis_{{ $port }}.log
    appendonly "no"
    save "\"\""
    dir /tmp
          {{- end }}
      {{- end}}
      {{- end}}
  {{- end}}
binaryData:
  redis_common.conf: >-
{{ include "redis.redis_common.conf" . | b64enc | indent 4 }}
